import Home from "./pages/Home";
import Navbar from "./components/Navbar";
import CollegeLogo from "./components/CollegeLogo";
import GeneralPara from "./components/GeneralPara";
import GeneralContainer from "./components/GeneralContainer";
import GeneralButton from "./components/GeneralButton";
import Footer from "./components/Footer";
import VideoBox from "./components/VideoBox";
import GeneralHeadingBox from "./components/GeneralHeadingBox";
export {Home,Navbar,CollegeLogo,GeneralPara,GeneralContainer,GeneralButton,Footer,VideoBox,GeneralHeadingBox};